# Generated by Django 5.2.12 on 2026-03-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_composition"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="入荷数量")),
                (
                    "remaining_quantity",
                    models.PositiveIntegerField(verbose_name="残数量"),
                ),
                ("arrived_at", models.DateField(verbose_name="入荷日")),
                ("expiry_date", models.DateField(verbose_name="品質維持期限")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "利用可能"),
                            ("near_expiry", "期限間近"),
                            ("expired", "期限切れ"),
                            ("depleted", "在庫切れ"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_lots",
                        to="products.item",
                        verbose_name="単品",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫ロット",
                "verbose_name_plural": "在庫ロット",
                "db_table": "inventory_stocklot",
                "ordering": ["expiry_date"],
            },
        ),
    ]
