# Generated by Django 5.2.12 on 2026-03-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='注文番号')),
                ('status', models.CharField(choices=[('pending', '保留中'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='届け先氏名')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=300, verbose_name='届け先住所')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('delivery_date', models.DateField(verbose_name='届け日')),
                ('message', models.TextField(blank=True, default='', verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名（注文時点）')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価（注文時点）')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
                'db_table': 'orders_order_line',
            },
        ),
    ]
