# Generated by Django 5.2.12 on 2026-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "保留中"),
                    ("confirmed", "確定"),
                    ("preparing", "出荷準備中"),
                    ("shipped", "出荷済み"),
                    ("cancelled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
