# Generated by Django 5.2.12 on 2026-03-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仕入先名')),
                ('contact_info', models.TextField(blank=True, default='', verbose_name='連絡先情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '仕入先',
                'verbose_name_plural': '仕入先',
                'db_table': 'products_supplier',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='単品名')),
                ('quality_retention_days', models.PositiveIntegerField(verbose_name='品質維持日数')),
                ('purchase_unit', models.PositiveIntegerField(verbose_name='購入単位')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='リードタイム（日）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '単品',
                'verbose_name_plural': '単品',
                'db_table': 'products_item',
            },
        ),
    ]
