# Generated by Django 5.2.12 on 2026-03-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='画像URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products_product',
            },
        ),
    ]
