# Generated by Django 5.2.12 on 2026-03-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='products.item', verbose_name='単品')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品構成',
                'verbose_name_plural': '商品構成',
                'db_table': 'products_composition',
                'constraints': [models.UniqueConstraint(fields=('product', 'item'), name='unique_product_item')],
            },
        ),
    ]
