# Generated by Django 5.2.12 on 2026-03-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_composition"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="発注数量")),
                ("expected_arrival_date", models.DateField(verbose_name="入荷予定日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "発注済み"),
                            ("arrived", "入荷済み"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="ordered",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発注日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="products.item",
                        verbose_name="単品",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="products.supplier",
                        verbose_name="仕入先",
                    ),
                ),
            ],
            options={
                "verbose_name": "発注",
                "verbose_name_plural": "発注",
                "db_table": "purchasing_purchase_order",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="Arrival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="入荷数量")),
                ("arrived_at", models.DateField(verbose_name="入荷日")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="products.item",
                        verbose_name="単品",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="purchasing.purchaseorder",
                        verbose_name="発注",
                    ),
                ),
            ],
            options={
                "verbose_name": "入荷",
                "verbose_name_plural": "入荷",
                "db_table": "purchasing_arrival",
                "ordering": ["-arrived_at"],
            },
        ),
    ]
