# Generated by Django 5.2.12 on 2026-03-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipped_at", models.DateTimeField(verbose_name="出荷日時")),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="通知日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment",
                        to="orders.order",
                        verbose_name="受注",
                    ),
                ),
            ],
            options={
                "verbose_name": "出荷",
                "verbose_name_plural": "出荷",
                "db_table": "shipping_shipment",
                "ordering": ["-shipped_at"],
            },
        ),
    ]
