sonar.projectKey=frere-memoire-webshop
sonar.projectName=フレール・メモワール WEB ショップ
sonar.sources=app
sonar.tests=spec
sonar.test.inclusions=**/*_spec.rb
sonar.exclusions=**/vendor/**,**/tmp/**,**/log/**,**/node_modules/**,**/db/schema.rb
sonar.sourceEncoding=UTF-8
sonar.ruby.coverage.reportPaths=coverage/.resultset.json
