spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webshop
    username: webshop
    password: webshop
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
