-- items テーブルのカラムリネーム（H2 互換）
ALTER TABLE items ALTER COLUMN shelf_life_days RENAME TO quality_retention_days;

-- 在庫テーブル
CREATE TABLE stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES items(id),
    quantity INTEGER NOT NULL,
    arrived_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_stocks_item_id ON stocks(item_id);
CREATE INDEX idx_stocks_expiry_date ON stocks(expiry_date);

-- 発注テーブル
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES items(id),
    supplier_name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL,
    desired_delivery_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ORDERED',
    ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);
CREATE INDEX idx_purchase_orders_item_id ON purchase_orders(item_id);

-- 入荷テーブル（IT5 で使用、テーブルのみ先行作成）
CREATE TABLE arrivals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id),
    item_id BIGINT NOT NULL REFERENCES items(id),
    quantity INTEGER NOT NULL,
    arrived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
