sonar.projectKey=fleur-memoire-backend
sonar.projectName=Fleur Memoire Backend
sonar.sources=apps,config
sonar.tests=apps,tests
sonar.test.inclusions=**/tests/**,**/test_*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/manage.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.language=py
